FROM node:slim

# We don't need the standalone Chromium
# ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
ENV PUPPETEER_SKIP_DOWNLOAD true

RUN apt-get update && apt-get install gnupg wget -y && \
  wget --quiet --output-document=- https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /etc/apt/trusted.gpg.d/google-archive.gpg && \
  sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
  apt-get update && \
  apt-get install google-chrome-stable -y --no-install-recommends && \
  apt-get install -y tzdata && \
  rm -rf /var/lib/apt/lists/*

# Установка временной зоны (замените на нужную)
ENV TZ=Europe/Moscow

WORKDIR /app

COPY package*.json /app/
COPY . .

# Установка зависимостей
RUN npm install

# Создание директорий для логов и сессий
RUN mkdir -p var/log && mkdir -p session/odin && mkdir -p screens

# Очистка после установки пакетов
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

EXPOSE 5000

ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable

CMD ["npm", "run", "start:dev"]