FROM node:lts as builder

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

RUN mkdir -p var/log

RUN mkdir -p session/odin

RUN npm ci

COPY . .

RUN npm run build

FROM node:lts-slim as final

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

RUN npm ci --only=production

RUN mkdir -p var/log

RUN mkdir -p session/odin

COPY --from=builder /usr/src/app/dist ./dist

EXPOSE 5000

CMD ["node", "dist/src/main.js"]
